### ISSUE TITLE
Editing Atlas settings/adding words to user dictionary while extension is loaded freezes Atlas

### ISSUE THREAD

**Issue by JML1981** [uyjulian/AtlasTranslate#1]
If I try and add word to my user dictionary while playing a game and having the atlas extension loaded, upon trying to add the word Atlas will just infinitely freeze and eventually crash or require a manual shut down of the process.  Just curious if this could be looked into so I could potentially run this extension and be able to add to my dictionary at the same time?  I tried running Atlas and Textractor in admin mode, see if that helped, but the same thing occurs.

**Comment by uyjulian** [comment]
Concurrent user access is not supported, as ATLAS is a single application accessing a database, not a database server.
